

    public enum UnitState
    {
        IDLE, RUNNING_FORWARD, RUNNING_BACKWARD, STRAFING_LEFT, STRAFING_RIGHT, RUNNING_FORWARD_LEFT, RUNNING_FORWARD_RIGHT, RUNNING_BACKWARDS_LEFT, RUNNING_BACKWARDS_RIGHT
    }
